<?php
/**
 * GENERATED FILE — DO NOT EDIT.
 *
 * Source of truth: pkg/agents in the WebDecoy/app repository. Regenerate with
 *   go run ./cmd/export-agent-registry -php
 * from that repository's pkg/ directory.
 *
 * ORDER IS SIGNIFICANT. Agents are in agents.MatchUserAgent order; a matcher
 * must take the first agent whose pattern the lower-cased User-Agent contains.
 */

declare(strict_types=1);

return [
    'schema' => 2,
    'agent_count' => 186,
    'categories' => ['training_crawler', 'ai_search_crawler', 'ai_agent', 'ai_assistant', 'search_crawler', 'seo_crawler', 'security_scanner', 'generic_scraper', 'archiver', 'fetcher', 'monitoring', 'headless_browser', 'feed_reader', 'commercial_scraper', 'none'],
    'agents' => [
        [
            'id' => 'reflectionbot',
            'name' => 'Reflectionbot',
            'category' => 'training_crawler',
            'behavior' => 'training',
            'organization' => 'Reflection AI',
            'patterns' => ['reflectionbot'],
            'robots_name' => 'Reflectionbot',
            'website' => 'https://reflection.ai',
            'base_score' => 70,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'gptbot',
            'name' => 'GPTBot',
            'category' => 'training_crawler',
            'behavior' => 'training',
            'organization' => 'OpenAI',
            'patterns' => ['gptbot'],
            'robots_name' => 'GPTBot',
            'website' => 'https://platform.openai.com/docs/gptbot',
            'base_score' => 85,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'claudebot',
            'name' => 'ClaudeBot',
            'category' => 'training_crawler',
            'behavior' => 'training',
            'organization' => 'Anthropic',
            'patterns' => ['claudebot'],
            'robots_name' => 'ClaudeBot',
            'website' => 'https://www.anthropic.com',
            'base_score' => 85,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'anthropic',
            'name' => 'Anthropic',
            'category' => 'training_crawler',
            'behavior' => 'training',
            'organization' => 'Anthropic',
            'patterns' => ['anthropic-ai'],
            'robots_name' => 'anthropic',
            'website' => 'https://www.anthropic.com',
            'base_score' => 85,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'claude-web',
            'name' => 'Claude-Web',
            'category' => 'training_crawler',
            'behavior' => 'training',
            'organization' => 'Anthropic',
            'patterns' => ['claude-web'],
            'robots_name' => 'Claude-Web',
            'website' => 'https://www.anthropic.com',
            'base_score' => 85,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'ccbot',
            'name' => 'CCBot',
            'category' => 'training_crawler',
            'behavior' => 'training',
            'organization' => 'Common Crawl',
            'patterns' => ['ccbot'],
            'robots_name' => 'CCBot',
            'website' => 'https://commoncrawl.org',
            'base_score' => 80,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'google-extended',
            'name' => 'Google-Extended',
            'category' => 'training_crawler',
            'behavior' => 'training',
            'organization' => 'Google',
            'patterns' => ['google-extended'],
            'robots_name' => 'Google-Extended',
            'website' => 'https://developers.google.com/search/docs/crawling-indexing/google-extended',
            'base_score' => 80,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'bytespider',
            'name' => 'ByteSpider',
            'category' => 'training_crawler',
            'behavior' => 'training',
            'organization' => 'ByteDance',
            'patterns' => ['bytespider'],
            'robots_name' => 'Bytespider',
            'website' => 'https://bytedance.com',
            'base_score' => 75,
            'respects_robots' => false,
            'http_client' => false,
        ],
        [
            'id' => 'amazonbot',
            'name' => 'Amazonbot',
            'category' => 'training_crawler',
            'behavior' => 'training',
            'organization' => 'Amazon',
            'patterns' => ['amazonbot'],
            'robots_name' => 'Amazonbot',
            'website' => 'https://developer.amazon.com/amazonbot',
            'base_score' => 70,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'facebookbot',
            'name' => 'FacebookBot',
            'category' => 'training_crawler',
            'behavior' => 'training',
            'organization' => 'Meta',
            'patterns' => ['facebookbot'],
            'robots_name' => 'FacebookBot',
            'website' => 'https://developers.facebook.com',
            'base_score' => 70,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'meta-externalagent',
            'name' => 'Meta-ExternalAgent',
            'category' => 'training_crawler',
            'behavior' => 'training',
            'organization' => 'Meta',
            'patterns' => ['meta-externalagent'],
            'robots_name' => 'Meta-ExternalAgent',
            'website' => 'https://meta.com',
            'base_score' => 75,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'cohere-ai',
            'name' => 'Cohere',
            'category' => 'training_crawler',
            'behavior' => 'training',
            'organization' => 'Cohere',
            'patterns' => ['cohere-ai', 'cohere'],
            'robots_name' => 'cohere-ai',
            'website' => 'https://cohere.ai',
            'base_score' => 80,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'applebot-extended',
            'name' => 'Applebot-Extended',
            'category' => 'training_crawler',
            'behavior' => 'training',
            'organization' => 'Apple',
            'patterns' => ['applebot-extended'],
            'robots_name' => 'Applebot-Extended',
            'website' => 'https://support.apple.com/applebot',
            'base_score' => 75,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'youbot',
            'name' => 'YouBot',
            'category' => 'training_crawler',
            'behavior' => 'training',
            'organization' => 'You.com',
            'patterns' => ['youbot'],
            'robots_name' => 'YouBot',
            'website' => 'https://you.com',
            'base_score' => 75,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'mistral',
            'name' => 'MistralBot',
            'category' => 'training_crawler',
            'behavior' => 'training',
            'organization' => 'Mistral AI',
            'patterns' => ['mistralbot'],
            'robots_name' => 'MistralBot',
            'website' => 'https://mistral.ai',
            'base_score' => 80,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'gemini',
            'name' => 'Gemini',
            'category' => 'training_crawler',
            'behavior' => 'training',
            'organization' => 'Google',
            'patterns' => ['gemini'],
            'robots_name' => 'Gemini',
            'website' => 'https://deepmind.google',
            'base_score' => 80,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'ai2bot',
            'name' => 'AI2Bot',
            'category' => 'training_crawler',
            'behavior' => 'training',
            'organization' => 'Allen Institute for AI',
            'patterns' => ['ai2bot'],
            'robots_name' => 'AI2Bot',
            'website' => 'https://allenai.org',
            'base_score' => 75,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'deepseek',
            'name' => 'DeepSeek',
            'category' => 'training_crawler',
            'behavior' => 'training',
            'organization' => 'DeepSeek',
            'patterns' => ['deepseek'],
            'robots_name' => 'DeepSeek',
            'website' => 'https://deepseek.com',
            'base_score' => 80,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'qwen',
            'name' => 'Qwen',
            'category' => 'training_crawler',
            'behavior' => 'training',
            'organization' => 'Alibaba',
            'patterns' => ['qwen'],
            'robots_name' => 'Qwen',
            'website' => 'https://qwenlm.github.io',
            'base_score' => 75,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'webzio',
            'name' => 'Webz.io',
            'category' => 'training_crawler',
            'behavior' => 'training',
            'organization' => 'Webz.io',
            'patterns' => ['webzio'],
            'robots_name' => 'webzio',
            'website' => 'https://webz.io',
            'base_score' => 70,
            'respects_robots' => false,
            'http_client' => false,
        ],
        [
            'id' => 'sentibot',
            'name' => 'Sentibot',
            'category' => 'training_crawler',
            'behavior' => 'training',
            'organization' => 'Sentibot',
            'patterns' => ['sentibot'],
            'robots_name' => 'Sentibot',
            'website' => '',
            'base_score' => 70,
            'respects_robots' => false,
            'http_client' => false,
        ],
        [
            'id' => 'omgili',
            'name' => 'Omgili',
            'category' => 'training_crawler',
            'behavior' => 'training',
            'organization' => 'Webz.io',
            'patterns' => ['omgili'],
            'robots_name' => 'omgili',
            'website' => 'https://omgili.com',
            'base_score' => 70,
            'respects_robots' => false,
            'http_client' => false,
        ],
        [
            'id' => 'img2dataset',
            'name' => 'img2dataset',
            'category' => 'training_crawler',
            'behavior' => 'training',
            'organization' => 'LAION',
            'patterns' => ['img2dataset'],
            'robots_name' => 'img2dataset',
            'website' => 'https://github.com/rom1504/img2dataset',
            'base_score' => 75,
            'respects_robots' => false,
            'http_client' => false,
        ],
        [
            'id' => 'timpibot',
            'name' => 'Timpibot',
            'category' => 'training_crawler',
            'behavior' => 'training',
            'organization' => 'Timpi',
            'patterns' => ['timpibot'],
            'robots_name' => 'Timpibot',
            'website' => 'https://timpi.io',
            'base_score' => 70,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'velenpublicwebcrawler',
            'name' => 'VelenPublicWebCrawler',
            'category' => 'training_crawler',
            'behavior' => 'training',
            'organization' => 'Velen',
            'patterns' => ['velenpublicwebcrawler'],
            'robots_name' => 'VelenPublicWebCrawler',
            'website' => '',
            'base_score' => 70,
            'respects_robots' => false,
            'http_client' => false,
        ],
        [
            'id' => 'isscyberriskcrawler',
            'name' => 'ISSCyberRiskCrawler',
            'category' => 'training_crawler',
            'behavior' => 'training',
            'organization' => 'ISS',
            'patterns' => ['isscyberriskcrawler'],
            'robots_name' => 'ISSCyberRiskCrawler',
            'website' => '',
            'base_score' => 65,
            'respects_robots' => false,
            'http_client' => false,
        ],
        [
            'id' => 'friendlycrawler',
            'name' => 'FriendlyCrawler',
            'category' => 'training_crawler',
            'behavior' => 'training',
            'organization' => 'Unknown',
            'patterns' => ['friendlycrawler'],
            'robots_name' => 'FriendlyCrawler',
            'website' => '',
            'base_score' => 65,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'duckassistbot',
            'name' => 'DuckAssistBot',
            'category' => 'ai_search_crawler',
            'behavior' => 'search',
            'organization' => 'DuckDuckGo',
            'patterns' => ['duckassistbot'],
            'robots_name' => 'DuckAssistBot',
            'website' => 'https://duckduckgo.com/duckassistbot.html',
            'base_score' => 65,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'sofyabot',
            'name' => 'SofyaBot',
            'category' => 'ai_search_crawler',
            'behavior' => 'search',
            'organization' => 'Sofya',
            'patterns' => ['sofyabot'],
            'robots_name' => 'SofyaBot',
            'website' => 'https://sofya.co/bot',
            'base_score' => 65,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'xai-searchbot',
            'name' => 'xAI-SearchBot',
            'category' => 'ai_search_crawler',
            'behavior' => 'search',
            'organization' => 'xAI',
            'patterns' => ['xai-searchbot'],
            'robots_name' => 'xAI-SearchBot',
            'website' => 'https://x.ai',
            'base_score' => 70,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'linkupbot',
            'name' => 'LinkupBot',
            'category' => 'ai_search_crawler',
            'behavior' => 'search',
            'organization' => 'Linkup',
            'patterns' => ['linkupbot'],
            'robots_name' => 'LinkupBot',
            'website' => 'https://linkup.so/bot',
            'base_score' => 65,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'perplexitybot',
            'name' => 'PerplexityBot',
            'category' => 'ai_search_crawler',
            'behavior' => 'search',
            'organization' => 'Perplexity AI',
            'patterns' => ['perplexitybot'],
            'robots_name' => 'PerplexityBot',
            'website' => 'https://docs.perplexity.ai/guides/bots',
            'base_score' => 80,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'claude-searchbot',
            'name' => 'Claude-SearchBot',
            'category' => 'ai_search_crawler',
            'behavior' => 'search',
            'organization' => 'Anthropic',
            'patterns' => ['claude-searchbot'],
            'robots_name' => 'Claude-SearchBot',
            'website' => 'https://support.claude.com/en/articles/8896518-does-anthropic-crawl-data-from-the-web-and-how-can-site-owners-block-the-crawler',
            'base_score' => 75,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'oai-searchbot',
            'name' => 'OAI-SearchBot',
            'category' => 'ai_search_crawler',
            'behavior' => 'search',
            'organization' => 'OpenAI',
            'patterns' => ['oai-searchbot'],
            'robots_name' => 'OAI-SearchBot',
            'website' => 'https://openai.com',
            'base_score' => 80,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'searchgpt',
            'name' => 'SearchGPT',
            'category' => 'ai_search_crawler',
            'behavior' => 'search',
            'organization' => 'OpenAI',
            'patterns' => ['searchgpt'],
            'robots_name' => 'SearchGPT',
            'website' => 'https://openai.com',
            'base_score' => 75,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'phind',
            'name' => 'Phind',
            'category' => 'ai_search_crawler',
            'behavior' => 'search',
            'organization' => 'Phind',
            'patterns' => ['phind'],
            'robots_name' => 'Phind',
            'website' => 'https://phind.com',
            'base_score' => 70,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'kagi',
            'name' => 'Kagi',
            'category' => 'ai_search_crawler',
            'behavior' => 'search',
            'organization' => 'Kagi',
            'patterns' => ['kagi'],
            'robots_name' => 'Kagi',
            'website' => 'https://kagi.com',
            'base_score' => 65,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'exa',
            'name' => 'Exa',
            'category' => 'ai_search_crawler',
            'behavior' => 'search',
            'organization' => 'Exa AI',
            'patterns' => ['exa.ai', 'exabot'],
            'robots_name' => 'Exa',
            'website' => 'https://exa.ai',
            'base_score' => 70,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'metaphor',
            'name' => 'Metaphor',
            'category' => 'ai_search_crawler',
            'behavior' => 'search',
            'organization' => 'Metaphor',
            'patterns' => ['metaphor'],
            'robots_name' => 'Metaphor',
            'website' => 'https://metaphor.systems',
            'base_score' => 70,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'tavily',
            'name' => 'Tavily',
            'category' => 'ai_search_crawler',
            'behavior' => 'search',
            'organization' => 'Tavily',
            'patterns' => ['tavily'],
            'robots_name' => 'Tavily',
            'website' => 'https://tavily.com',
            'base_score' => 70,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'brave-search',
            'name' => 'BraveSearch',
            'category' => 'ai_search_crawler',
            'behavior' => 'search',
            'organization' => 'Brave',
            'patterns' => ['bravesearch'],
            'robots_name' => 'BraveSearch',
            'website' => 'https://search.brave.com',
            'base_score' => 65,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'neeva',
            'name' => 'NeevaBot',
            'category' => 'ai_search_crawler',
            'behavior' => 'search',
            'organization' => 'Neeva',
            'patterns' => ['neevabot'],
            'robots_name' => 'NeevaBot',
            'website' => 'https://neeva.com',
            'base_score' => 65,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'operator',
            'name' => 'Operator',
            'category' => 'ai_agent',
            'behavior' => 'agent',
            'organization' => 'OpenAI',
            'patterns' => ['operator'],
            'robots_name' => 'Operator',
            'website' => 'https://openai.com',
            'base_score' => 75,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'claude-user',
            'name' => 'Claude-User',
            'category' => 'ai_agent',
            'behavior' => 'agent',
            'organization' => 'Anthropic',
            'patterns' => ['claude-user'],
            'robots_name' => 'Claude-User',
            'website' => 'https://anthropic.com',
            'base_score' => 75,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'gemini-user',
            'name' => 'Gemini-User',
            'category' => 'ai_agent',
            'behavior' => 'agent',
            'organization' => 'Google',
            'patterns' => ['gemini-user'],
            'robots_name' => 'Gemini-User',
            'website' => 'https://gemini.google.com',
            'base_score' => 75,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'googleagent-mariner',
            'name' => 'GoogleAgent-Mariner',
            'category' => 'ai_agent',
            'behavior' => 'agent',
            'organization' => 'Google',
            'patterns' => ['googleagent-mariner', 'mariner'],
            'robots_name' => 'GoogleAgent-Mariner',
            'website' => 'https://deepmind.google',
            'base_score' => 75,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'amazon-buyforme',
            'name' => 'AmazonBuyForMe',
            'category' => 'ai_agent',
            'behavior' => 'agent',
            'organization' => 'Amazon',
            'patterns' => ['amazonbuyforme', 'buyforme'],
            'robots_name' => 'AmazonBuyForMe',
            'website' => 'https://amazon.com',
            'base_score' => 70,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'browser-use',
            'name' => 'Browser-Use',
            'category' => 'ai_agent',
            'behavior' => 'agent',
            'organization' => 'Open Source',
            'patterns' => ['browser-use'],
            'robots_name' => 'Browser-Use',
            'website' => 'https://github.com/browser-use/browser-use',
            'base_score' => 70,
            'respects_robots' => false,
            'http_client' => false,
        ],
        [
            'id' => 'stagehand',
            'name' => 'Stagehand',
            'category' => 'ai_agent',
            'behavior' => 'agent',
            'organization' => 'Browserbase',
            'patterns' => ['stagehand'],
            'robots_name' => 'Stagehand',
            'website' => 'https://browserbase.com',
            'base_score' => 70,
            'respects_robots' => false,
            'http_client' => false,
        ],
        [
            'id' => 'multion',
            'name' => 'MultiOn',
            'category' => 'ai_agent',
            'behavior' => 'agent',
            'organization' => 'MultiOn',
            'patterns' => ['multion'],
            'robots_name' => 'MultiOn',
            'website' => 'https://multion.ai',
            'base_score' => 70,
            'respects_robots' => false,
            'http_client' => false,
        ],
        [
            'id' => 'iboubot',
            'name' => 'IbouBot',
            'category' => 'search_crawler',
            'behavior' => 'search',
            'organization' => 'Ibou',
            'patterns' => ['iboubot'],
            'robots_name' => 'IbouBot',
            'website' => 'https://ibou.io/iboubot.html',
            'base_score' => 30,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'googlebot',
            'name' => 'Googlebot',
            'category' => 'search_crawler',
            'behavior' => 'search',
            'organization' => 'Google',
            'patterns' => ['googlebot'],
            'robots_name' => 'Googlebot',
            'website' => 'https://developers.google.com/search/docs/crawling-indexing/googlebot',
            'base_score' => 30,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'google-inspectiontool',
            'name' => 'Google-InspectionTool',
            'category' => 'search_crawler',
            'behavior' => 'search',
            'organization' => 'Google',
            'patterns' => ['google-inspectiontool'],
            'robots_name' => 'Google-InspectionTool',
            'website' => 'https://developers.google.com/search/docs/crawling-indexing/google-common-crawlers',
            'base_score' => 30,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'bingbot',
            'name' => 'Bingbot',
            'category' => 'search_crawler',
            'behavior' => 'search',
            'organization' => 'Microsoft',
            'patterns' => ['bingbot'],
            'robots_name' => 'Bingbot',
            'website' => 'https://www.bing.com/webmasters/help/bingbot',
            'base_score' => 30,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'msnbot',
            'name' => 'MSNBot',
            'category' => 'search_crawler',
            'behavior' => 'search',
            'organization' => 'Microsoft',
            'patterns' => ['msnbot'],
            'robots_name' => 'msnbot',
            'website' => 'https://www.bing.com/webmasters/help/which-crawlers-does-bing-use-8c184ec0',
            'base_score' => 30,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'yandexbot',
            'name' => 'YandexBot',
            'category' => 'search_crawler',
            'behavior' => 'search',
            'organization' => 'Yandex',
            'patterns' => ['yandexbot'],
            'robots_name' => 'YandexBot',
            'website' => 'https://yandex.com/support/webmaster/robot-workings/',
            'base_score' => 35,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'baiduspider',
            'name' => 'Baiduspider',
            'category' => 'search_crawler',
            'behavior' => 'search',
            'organization' => 'Baidu',
            'patterns' => ['baiduspider'],
            'robots_name' => 'Baiduspider',
            'website' => 'https://www.baidu.com/search/spider.html',
            'base_score' => 40,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'duckduckbot',
            'name' => 'DuckDuckBot',
            'category' => 'search_crawler',
            'behavior' => 'search',
            'organization' => 'DuckDuckGo',
            'patterns' => ['duckduckbot'],
            'robots_name' => 'DuckDuckBot',
            'website' => 'https://duckduckgo.com/duckduckbot',
            'base_score' => 30,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'applebot',
            'name' => 'Applebot',
            'category' => 'search_crawler',
            'behavior' => 'search',
            'organization' => 'Apple',
            'patterns' => ['applebot'],
            'robots_name' => 'Applebot',
            'website' => 'https://support.apple.com/applebot',
            'base_score' => 30,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'sogou',
            'name' => 'Sogou Spider',
            'category' => 'search_crawler',
            'behavior' => 'search',
            'organization' => 'Sogou',
            'patterns' => ['sogou'],
            'robots_name' => 'Sogou',
            'website' => 'https://sogou.com',
            'base_score' => 40,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'qwantify',
            'name' => 'Qwantify',
            'category' => 'search_crawler',
            'behavior' => 'search',
            'organization' => 'Qwant',
            'patterns' => ['qwantify'],
            'robots_name' => 'Qwantify',
            'website' => 'https://qwant.com',
            'base_score' => 35,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'naver',
            'name' => 'Naver',
            'category' => 'search_crawler',
            'behavior' => 'search',
            'organization' => 'Naver',
            'patterns' => ['naver', 'yeti'],
            'robots_name' => 'Naver',
            'website' => 'https://naver.com',
            'base_score' => 35,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'seznam',
            'name' => 'SeznamBot',
            'category' => 'search_crawler',
            'behavior' => 'search',
            'organization' => 'Seznam',
            'patterns' => ['seznambot'],
            'robots_name' => 'SeznamBot',
            'website' => 'https://seznam.cz',
            'base_score' => 35,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'ecosia',
            'name' => 'Ecosia',
            'category' => 'search_crawler',
            'behavior' => 'search',
            'organization' => 'Ecosia',
            'patterns' => ['ecosia'],
            'robots_name' => 'Ecosia',
            'website' => 'https://ecosia.org',
            'base_score' => 30,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'mojeek',
            'name' => 'MojeekBot',
            'category' => 'search_crawler',
            'behavior' => 'search',
            'organization' => 'Mojeek',
            'patterns' => ['mojeekbot'],
            'robots_name' => 'MojeekBot',
            'website' => 'https://mojeek.com',
            'base_score' => 35,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'yahoo-slurp',
            'name' => 'Yahoo! Slurp',
            'category' => 'search_crawler',
            'behavior' => 'search',
            'organization' => 'Yahoo',
            'patterns' => ['slurp'],
            'robots_name' => 'Slurp',
            'website' => 'https://yahoo.com',
            'base_score' => 30,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'ahrefsbot',
            'name' => 'AhrefsBot',
            'category' => 'seo_crawler',
            'behavior' => 'seo',
            'organization' => 'Ahrefs',
            'patterns' => ['ahrefsbot', 'ahrefs'],
            'robots_name' => 'AhrefsBot',
            'website' => 'https://ahrefs.com/robot',
            'base_score' => 50,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'semrushbot',
            'name' => 'SemrushBot',
            'category' => 'seo_crawler',
            'behavior' => 'seo',
            'organization' => 'Semrush',
            'patterns' => ['semrushbot', 'semrush'],
            'robots_name' => 'SemrushBot',
            'website' => 'https://semrush.com/bot',
            'base_score' => 50,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'mj12bot',
            'name' => 'MJ12bot',
            'category' => 'seo_crawler',
            'behavior' => 'seo',
            'organization' => 'Majestic',
            'patterns' => ['mj12bot'],
            'robots_name' => 'MJ12bot',
            'website' => 'https://majestic.com/bot',
            'base_score' => 50,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'dotbot',
            'name' => 'DotBot',
            'category' => 'seo_crawler',
            'behavior' => 'seo',
            'organization' => 'Moz',
            'patterns' => ['dotbot'],
            'robots_name' => 'DotBot',
            'website' => 'https://moz.com/help/moz-procedures/crawlers',
            'base_score' => 50,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'rogerbot',
            'name' => 'Rogerbot',
            'category' => 'seo_crawler',
            'behavior' => 'seo',
            'organization' => 'Moz',
            'patterns' => ['rogerbot'],
            'robots_name' => 'rogerbot',
            'website' => 'https://moz.com/help/moz-procedures/crawlers',
            'base_score' => 50,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'screaming-frog',
            'name' => 'Screaming Frog',
            'category' => 'seo_crawler',
            'behavior' => 'seo',
            'organization' => 'Screaming Frog',
            'patterns' => ['screaming frog'],
            'robots_name' => 'Screaming Frog SEO Spider',
            'website' => 'https://screamingfrog.co.uk',
            'base_score' => 55,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'sitebulb',
            'name' => 'Sitebulb',
            'category' => 'seo_crawler',
            'behavior' => 'seo',
            'organization' => 'Sitebulb',
            'patterns' => ['sitebulb'],
            'robots_name' => 'Sitebulb',
            'website' => 'https://sitebulb.com',
            'base_score' => 55,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'deepcrawl',
            'name' => 'DeepCrawl',
            'category' => 'seo_crawler',
            'behavior' => 'seo',
            'organization' => 'Lumar',
            'patterns' => ['deepcrawl'],
            'robots_name' => 'DeepCrawl',
            'website' => 'https://lumar.io',
            'base_score' => 50,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'oncrawl',
            'name' => 'OnCrawl',
            'category' => 'seo_crawler',
            'behavior' => 'seo',
            'organization' => 'OnCrawl',
            'patterns' => ['oncrawl'],
            'robots_name' => 'OnCrawl',
            'website' => 'https://oncrawl.com',
            'base_score' => 50,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'botify',
            'name' => 'Botify',
            'category' => 'seo_crawler',
            'behavior' => 'seo',
            'organization' => 'Botify',
            'patterns' => ['botify'],
            'robots_name' => 'Botify',
            'website' => 'https://botify.com',
            'base_score' => 50,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'contentking',
            'name' => 'ContentKing',
            'category' => 'seo_crawler',
            'behavior' => 'seo',
            'organization' => 'ContentKing',
            'patterns' => ['contentking'],
            'robots_name' => 'ContentKing',
            'website' => 'https://contentkingapp.com',
            'base_score' => 50,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'sistrix',
            'name' => 'SISTRIX',
            'category' => 'seo_crawler',
            'behavior' => 'seo',
            'organization' => 'SISTRIX',
            'patterns' => ['sistrix'],
            'robots_name' => 'SISTRIX',
            'website' => 'https://sistrix.com',
            'base_score' => 50,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'serpstat',
            'name' => 'Serpstat',
            'category' => 'seo_crawler',
            'behavior' => 'seo',
            'organization' => 'Serpstat',
            'patterns' => ['serpstat'],
            'robots_name' => 'Serpstat',
            'website' => 'https://serpstat.com',
            'base_score' => 50,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'spyfu',
            'name' => 'SpyFu',
            'category' => 'seo_crawler',
            'behavior' => 'seo',
            'organization' => 'SpyFu',
            'patterns' => ['spyfu'],
            'robots_name' => 'SpyFu',
            'website' => 'https://spyfu.com',
            'base_score' => 50,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'nessus',
            'name' => 'Nessus',
            'category' => 'security_scanner',
            'behavior' => 'security_testing',
            'organization' => 'Tenable',
            'patterns' => ['nessus'],
            'robots_name' => 'Nessus',
            'website' => 'https://tenable.com',
            'base_score' => 70,
            'respects_robots' => false,
            'http_client' => false,
        ],
        [
            'id' => 'qualys',
            'name' => 'Qualys',
            'category' => 'security_scanner',
            'behavior' => 'security_testing',
            'organization' => 'Qualys',
            'patterns' => ['qualys'],
            'robots_name' => 'Qualys',
            'website' => 'https://qualys.com',
            'base_score' => 70,
            'respects_robots' => false,
            'http_client' => false,
        ],
        [
            'id' => 'shodan',
            'name' => 'Shodan',
            'category' => 'security_scanner',
            'behavior' => 'security_testing',
            'organization' => 'Shodan',
            'patterns' => ['shodan'],
            'robots_name' => 'Shodan',
            'website' => 'https://shodan.io',
            'base_score' => 75,
            'respects_robots' => false,
            'http_client' => false,
        ],
        [
            'id' => 'censys',
            'name' => 'Censys',
            'category' => 'security_scanner',
            'behavior' => 'security_testing',
            'organization' => 'Censys',
            'patterns' => ['censys'],
            'robots_name' => 'Censys',
            'website' => 'https://censys.io',
            'base_score' => 75,
            'respects_robots' => false,
            'http_client' => false,
        ],
        [
            'id' => 'nmap',
            'name' => 'Nmap',
            'category' => 'security_scanner',
            'behavior' => 'security_testing',
            'organization' => 'Open Source',
            'patterns' => ['nmap'],
            'robots_name' => 'Nmap',
            'website' => 'https://nmap.org',
            'base_score' => 70,
            'respects_robots' => false,
            'http_client' => false,
        ],
        [
            'id' => 'zap',
            'name' => 'OWASP ZAP',
            'category' => 'security_scanner',
            'behavior' => 'security_testing',
            'organization' => 'OWASP',
            'patterns' => ['zap/'],
            'robots_name' => 'ZAP',
            'website' => 'https://zaproxy.org',
            'base_score' => 70,
            'respects_robots' => false,
            'http_client' => false,
        ],
        [
            'id' => 'burp',
            'name' => 'Burp Suite',
            'category' => 'security_scanner',
            'behavior' => 'security_testing',
            'organization' => 'PortSwigger',
            'patterns' => ['burp'],
            'robots_name' => 'Burp',
            'website' => 'https://portswigger.net/burp',
            'base_score' => 70,
            'respects_robots' => false,
            'http_client' => false,
        ],
        [
            'id' => 'nikto',
            'name' => 'Nikto',
            'category' => 'security_scanner',
            'behavior' => 'security_testing',
            'organization' => 'Open Source',
            'patterns' => ['nikto'],
            'robots_name' => 'Nikto',
            'website' => 'https://cirt.net/Nikto2',
            'base_score' => 70,
            'respects_robots' => false,
            'http_client' => false,
        ],
        [
            'id' => 'nuclei',
            'name' => 'Nuclei',
            'category' => 'security_scanner',
            'behavior' => 'security_testing',
            'organization' => 'ProjectDiscovery',
            'patterns' => ['nuclei'],
            'robots_name' => 'Nuclei',
            'website' => 'https://nuclei.projectdiscovery.io',
            'base_score' => 70,
            'respects_robots' => false,
            'http_client' => false,
        ],
        [
            'id' => 'acunetix',
            'name' => 'Acunetix',
            'category' => 'security_scanner',
            'behavior' => 'security_testing',
            'organization' => 'Invicti',
            'patterns' => ['acunetix'],
            'robots_name' => 'Acunetix',
            'website' => 'https://acunetix.com',
            'base_score' => 70,
            'respects_robots' => false,
            'http_client' => false,
        ],
        [
            'id' => 'netsparker',
            'name' => 'Netsparker',
            'category' => 'security_scanner',
            'behavior' => 'security_testing',
            'organization' => 'Invicti',
            'patterns' => ['netsparker'],
            'robots_name' => 'Netsparker',
            'website' => 'https://netsparker.com',
            'base_score' => 70,
            'respects_robots' => false,
            'http_client' => false,
        ],
        [
            'id' => 'detectify',
            'name' => 'Detectify',
            'category' => 'security_scanner',
            'behavior' => 'security_testing',
            'organization' => 'Detectify',
            'patterns' => ['detectify'],
            'robots_name' => 'Detectify',
            'website' => 'https://detectify.com',
            'base_score' => 65,
            'respects_robots' => false,
            'http_client' => false,
        ],
        [
            'id' => 'intruder',
            'name' => 'Intruder',
            'category' => 'security_scanner',
            'behavior' => 'security_testing',
            'organization' => 'Intruder',
            'patterns' => ['intruder'],
            'robots_name' => 'Intruder',
            'website' => 'https://intruder.io',
            'base_score' => 65,
            'respects_robots' => false,
            'http_client' => false,
        ],
        [
            'id' => 'python-requests',
            'name' => 'Python-Requests',
            'category' => 'generic_scraper',
            'behavior' => '',
            'organization' => 'Open Source',
            'patterns' => ['python-requests'],
            'robots_name' => '',
            'website' => 'https://requests.readthedocs.io',
            'base_score' => 55,
            'respects_robots' => false,
            'http_client' => true,
        ],
        [
            'id' => 'python-urllib',
            'name' => 'Python-urllib',
            'category' => 'generic_scraper',
            'behavior' => '',
            'organization' => 'Python',
            'patterns' => ['python-urllib'],
            'robots_name' => '',
            'website' => 'https://docs.python.org/3/library/urllib.html',
            'base_score' => 55,
            'respects_robots' => false,
            'http_client' => true,
        ],
        [
            'id' => 'python',
            'name' => 'Python',
            'category' => 'generic_scraper',
            'behavior' => '',
            'organization' => 'Python',
            'patterns' => ['python/'],
            'robots_name' => '',
            'website' => 'https://python.org',
            'base_score' => 50,
            'respects_robots' => false,
            'http_client' => true,
        ],
        [
            'id' => 'scrapy',
            'name' => 'Scrapy',
            'category' => 'generic_scraper',
            'behavior' => '',
            'organization' => 'Scrapy',
            'patterns' => ['scrapy'],
            'robots_name' => 'Scrapy',
            'website' => 'https://scrapy.org',
            'base_score' => 65,
            'respects_robots' => true,
            'http_client' => true,
        ],
        [
            'id' => 'httpx',
            'name' => 'HTTPX',
            'category' => 'generic_scraper',
            'behavior' => '',
            'organization' => 'Open Source',
            'patterns' => ['httpx'],
            'robots_name' => '',
            'website' => 'https://www.python-httpx.org',
            'base_score' => 55,
            'respects_robots' => false,
            'http_client' => true,
        ],
        [
            'id' => 'aiohttp',
            'name' => 'aiohttp',
            'category' => 'generic_scraper',
            'behavior' => '',
            'organization' => 'Open Source',
            'patterns' => ['aiohttp'],
            'robots_name' => '',
            'website' => 'https://docs.aiohttp.org',
            'base_score' => 55,
            'respects_robots' => false,
            'http_client' => true,
        ],
        [
            'id' => 'beautifulsoup',
            'name' => 'BeautifulSoup',
            'category' => 'generic_scraper',
            'behavior' => '',
            'organization' => 'Open Source',
            'patterns' => ['beautifulsoup'],
            'robots_name' => '',
            'website' => 'https://beautiful-soup-4.readthedocs.io',
            'base_score' => 60,
            'respects_robots' => false,
            'http_client' => true,
        ],
        [
            'id' => 'node-fetch',
            'name' => 'node-fetch',
            'category' => 'generic_scraper',
            'behavior' => '',
            'organization' => 'Open Source',
            'patterns' => ['node-fetch'],
            'robots_name' => '',
            'website' => 'https://github.com/node-fetch/node-fetch',
            'base_score' => 55,
            'respects_robots' => false,
            'http_client' => true,
        ],
        [
            'id' => 'axios',
            'name' => 'Axios',
            'category' => 'generic_scraper',
            'behavior' => '',
            'organization' => 'Open Source',
            'patterns' => ['axios/'],
            'robots_name' => '',
            'website' => 'https://axios-http.com',
            'base_score' => 55,
            'respects_robots' => false,
            'http_client' => true,
        ],
        [
            'id' => 'got',
            'name' => 'Got',
            'category' => 'generic_scraper',
            'behavior' => '',
            'organization' => 'Open Source',
            'patterns' => ['got/'],
            'robots_name' => '',
            'website' => 'https://github.com/sindresorhus/got',
            'base_score' => 55,
            'respects_robots' => false,
            'http_client' => true,
        ],
        [
            'id' => 'undici',
            'name' => 'Undici',
            'category' => 'generic_scraper',
            'behavior' => '',
            'organization' => 'Node.js',
            'patterns' => ['undici'],
            'robots_name' => '',
            'website' => 'https://undici.nodejs.org',
            'base_score' => 55,
            'respects_robots' => false,
            'http_client' => true,
        ],
        [
            'id' => 'go-http-client',
            'name' => 'Go-HTTP-Client',
            'category' => 'generic_scraper',
            'behavior' => '',
            'organization' => 'Go',
            'patterns' => ['go-http-client'],
            'robots_name' => '',
            'website' => 'https://golang.org',
            'base_score' => 55,
            'respects_robots' => false,
            'http_client' => true,
        ],
        [
            'id' => 'colly',
            'name' => 'Colly',
            'category' => 'generic_scraper',
            'behavior' => '',
            'organization' => 'Open Source',
            'patterns' => ['colly'],
            'robots_name' => 'Colly',
            'website' => 'https://go-colly.org',
            'base_score' => 65,
            'respects_robots' => true,
            'http_client' => true,
        ],
        [
            'id' => 'java',
            'name' => 'Java',
            'category' => 'generic_scraper',
            'behavior' => '',
            'organization' => 'Oracle',
            'patterns' => ['java/'],
            'robots_name' => '',
            'website' => 'https://java.com',
            'base_score' => 50,
            'respects_robots' => false,
            'http_client' => true,
        ],
        [
            'id' => 'okhttp',
            'name' => 'OkHttp',
            'category' => 'generic_scraper',
            'behavior' => '',
            'organization' => 'Square',
            'patterns' => ['okhttp'],
            'robots_name' => '',
            'website' => 'https://square.github.io/okhttp/',
            'base_score' => 55,
            'respects_robots' => false,
            'http_client' => true,
        ],
        [
            'id' => 'apache-httpclient',
            'name' => 'Apache-HttpClient',
            'category' => 'generic_scraper',
            'behavior' => '',
            'organization' => 'Apache',
            'patterns' => ['apache-httpclient'],
            'robots_name' => '',
            'website' => 'https://hc.apache.org',
            'base_score' => 55,
            'respects_robots' => false,
            'http_client' => true,
        ],
        [
            'id' => 'jsoup',
            'name' => 'Jsoup',
            'category' => 'generic_scraper',
            'behavior' => '',
            'organization' => 'Open Source',
            'patterns' => ['jsoup'],
            'robots_name' => '',
            'website' => 'https://jsoup.org',
            'base_score' => 60,
            'respects_robots' => false,
            'http_client' => true,
        ],
        [
            'id' => 'guzzlehttp',
            'name' => 'GuzzleHttp',
            'category' => 'generic_scraper',
            'behavior' => '',
            'organization' => 'Open Source',
            'patterns' => ['guzzlehttp'],
            'robots_name' => '',
            'website' => 'https://docs.guzzlephp.org',
            'base_score' => 55,
            'respects_robots' => false,
            'http_client' => true,
        ],
        [
            'id' => 'php',
            'name' => 'PHP',
            'category' => 'generic_scraper',
            'behavior' => '',
            'organization' => 'PHP',
            'patterns' => ['php/'],
            'robots_name' => '',
            'website' => 'https://php.net',
            'base_score' => 50,
            'respects_robots' => false,
            'http_client' => true,
        ],
        [
            'id' => 'ruby',
            'name' => 'Ruby',
            'category' => 'generic_scraper',
            'behavior' => '',
            'organization' => 'Ruby',
            'patterns' => ['ruby'],
            'robots_name' => '',
            'website' => 'https://ruby-lang.org',
            'base_score' => 50,
            'respects_robots' => false,
            'http_client' => true,
        ],
        [
            'id' => 'faraday',
            'name' => 'Faraday',
            'category' => 'generic_scraper',
            'behavior' => '',
            'organization' => 'Open Source',
            'patterns' => ['faraday'],
            'robots_name' => '',
            'website' => 'https://lostisland.github.io/faraday/',
            'base_score' => 55,
            'respects_robots' => false,
            'http_client' => true,
        ],
        [
            'id' => 'mechanize',
            'name' => 'Mechanize',
            'category' => 'generic_scraper',
            'behavior' => '',
            'organization' => 'Open Source',
            'patterns' => ['mechanize'],
            'robots_name' => '',
            'website' => '',
            'base_score' => 60,
            'respects_robots' => false,
            'http_client' => true,
        ],
        [
            'id' => 'headlesschrome',
            'name' => 'HeadlessChrome',
            'category' => 'headless_browser',
            'behavior' => '',
            'organization' => 'Google',
            'patterns' => ['headlesschrome'],
            'robots_name' => '',
            'website' => 'https://developers.google.com/web/updates/2017/04/headless-chrome',
            'base_score' => 70,
            'respects_robots' => false,
            'http_client' => true,
        ],
        [
            'id' => 'puppeteer',
            'name' => 'Puppeteer',
            'category' => 'headless_browser',
            'behavior' => '',
            'organization' => 'Google',
            'patterns' => ['puppeteer'],
            'robots_name' => '',
            'website' => 'https://pptr.dev',
            'base_score' => 70,
            'respects_robots' => false,
            'http_client' => true,
        ],
        [
            'id' => 'playwright',
            'name' => 'Playwright',
            'category' => 'headless_browser',
            'behavior' => '',
            'organization' => 'Microsoft',
            'patterns' => ['playwright'],
            'robots_name' => '',
            'website' => 'https://playwright.dev',
            'base_score' => 70,
            'respects_robots' => false,
            'http_client' => true,
        ],
        [
            'id' => 'selenium',
            'name' => 'Selenium',
            'category' => 'headless_browser',
            'behavior' => '',
            'organization' => 'Open Source',
            'patterns' => ['selenium'],
            'robots_name' => '',
            'website' => 'https://selenium.dev',
            'base_score' => 70,
            'respects_robots' => false,
            'http_client' => true,
        ],
        [
            'id' => 'phantomjs',
            'name' => 'PhantomJS',
            'category' => 'headless_browser',
            'behavior' => '',
            'organization' => 'Open Source',
            'patterns' => ['phantomjs'],
            'robots_name' => '',
            'website' => 'https://phantomjs.org',
            'base_score' => 75,
            'respects_robots' => false,
            'http_client' => true,
        ],
        [
            'id' => 'splash',
            'name' => 'Splash',
            'category' => 'headless_browser',
            'behavior' => '',
            'organization' => 'Scrapinghub',
            'patterns' => ['splash'],
            'robots_name' => '',
            'website' => 'https://splash.readthedocs.io',
            'base_score' => 70,
            'respects_robots' => false,
            'http_client' => true,
        ],
        [
            'id' => 'browserless',
            'name' => 'Browserless',
            'category' => 'headless_browser',
            'behavior' => '',
            'organization' => 'Browserless',
            'patterns' => ['browserless'],
            'robots_name' => '',
            'website' => 'https://browserless.io',
            'base_score' => 65,
            'respects_robots' => false,
            'http_client' => true,
        ],
        [
            'id' => 'browserbase',
            'name' => 'Browserbase',
            'category' => 'headless_browser',
            'behavior' => '',
            'organization' => 'Browserbase',
            'patterns' => ['browserbase'],
            'robots_name' => '',
            'website' => 'https://browserbase.com',
            'base_score' => 65,
            'respects_robots' => false,
            'http_client' => true,
        ],
        [
            'id' => 'ia-archiver',
            'name' => 'Internet Archive',
            'category' => 'archiver',
            'behavior' => 'other',
            'organization' => 'Internet Archive',
            'patterns' => ['ia_archiver'],
            'robots_name' => 'ia_archiver',
            'website' => 'https://archive.org',
            'base_score' => 25,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'archive-org-bot',
            'name' => 'Archive.org',
            'category' => 'archiver',
            'behavior' => 'other',
            'organization' => 'Internet Archive',
            'patterns' => ['archive.org_bot'],
            'robots_name' => 'archive.org_bot',
            'website' => 'https://archive.org',
            'base_score' => 25,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'wayback',
            'name' => 'Wayback Machine',
            'category' => 'archiver',
            'behavior' => 'other',
            'organization' => 'Internet Archive',
            'patterns' => ['wayback'],
            'robots_name' => 'Wayback',
            'website' => 'https://web.archive.org',
            'base_score' => 25,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'heritrix',
            'name' => 'Heritrix',
            'category' => 'archiver',
            'behavior' => 'other',
            'organization' => 'Internet Archive',
            'patterns' => ['heritrix'],
            'robots_name' => 'Heritrix',
            'website' => 'https://github.com/internetarchive/heritrix3',
            'base_score' => 30,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'brozzler',
            'name' => 'Brozzler',
            'category' => 'archiver',
            'behavior' => 'other',
            'organization' => 'Internet Archive',
            'patterns' => ['brozzler'],
            'robots_name' => 'Brozzler',
            'website' => 'https://github.com/internetarchive/brozzler',
            'base_score' => 30,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'facebookexternalhit',
            'name' => 'Facebook',
            'category' => 'fetcher',
            'behavior' => 'link_preview',
            'organization' => 'Meta',
            'patterns' => ['facebookexternalhit'],
            'robots_name' => 'facebookexternalhit',
            'website' => 'https://developers.facebook.com/docs/sharing/webmasters/crawler',
            'base_score' => 25,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'facebot',
            'name' => 'Facebot',
            'category' => 'fetcher',
            'behavior' => 'link_preview',
            'organization' => 'Meta',
            'patterns' => ['facebot'],
            'robots_name' => 'Facebot',
            'website' => 'https://developers.facebook.com/docs/sharing/webmasters/crawler',
            'base_score' => 25,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'twitterbot',
            'name' => 'Twitterbot',
            'category' => 'fetcher',
            'behavior' => 'link_preview',
            'organization' => 'X Corp',
            'patterns' => ['twitterbot'],
            'robots_name' => 'Twitterbot',
            'website' => 'https://developer.twitter.com',
            'base_score' => 25,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'linkedinbot',
            'name' => 'LinkedInBot',
            'category' => 'fetcher',
            'behavior' => 'link_preview',
            'organization' => 'LinkedIn',
            'patterns' => ['linkedinbot'],
            'robots_name' => 'LinkedInBot',
            'website' => 'https://linkedin.com',
            'base_score' => 25,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'slackbot',
            'name' => 'Slackbot',
            'category' => 'fetcher',
            'behavior' => 'link_preview',
            'organization' => 'Slack',
            'patterns' => ['slackbot'],
            'robots_name' => 'Slackbot',
            'website' => 'https://api.slack.com/robots',
            'base_score' => 25,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'telegrambot',
            'name' => 'TelegramBot',
            'category' => 'fetcher',
            'behavior' => 'link_preview',
            'organization' => 'Telegram',
            'patterns' => ['telegrambot'],
            'robots_name' => 'TelegramBot',
            'website' => 'https://telegram.org',
            'base_score' => 25,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'whatsapp',
            'name' => 'WhatsApp',
            'category' => 'fetcher',
            'behavior' => 'link_preview',
            'organization' => 'Meta',
            'patterns' => ['whatsapp'],
            'robots_name' => 'WhatsApp',
            'website' => 'https://whatsapp.com',
            'base_score' => 25,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'discordbot',
            'name' => 'Discordbot',
            'category' => 'fetcher',
            'behavior' => 'link_preview',
            'organization' => 'Discord',
            'patterns' => ['discordbot'],
            'robots_name' => 'Discordbot',
            'website' => 'https://discord.com',
            'base_score' => 25,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'pinterestbot',
            'name' => 'Pinterest',
            'category' => 'fetcher',
            'behavior' => 'link_preview',
            'organization' => 'Pinterest',
            'patterns' => ['pinterest'],
            'robots_name' => 'Pinterest',
            'website' => 'https://pinterest.com',
            'base_score' => 30,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'tumblr',
            'name' => 'Tumblr',
            'category' => 'fetcher',
            'behavior' => 'link_preview',
            'organization' => 'Automattic',
            'patterns' => ['tumblr'],
            'robots_name' => 'Tumblr',
            'website' => 'https://tumblr.com',
            'base_score' => 30,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'reddit',
            'name' => 'Reddit',
            'category' => 'fetcher',
            'behavior' => 'link_preview',
            'organization' => 'Reddit',
            'patterns' => ['reddit'],
            'robots_name' => 'Redditbot',
            'website' => 'https://reddit.com',
            'base_score' => 30,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'embedly',
            'name' => 'Embedly',
            'category' => 'fetcher',
            'behavior' => 'link_preview',
            'organization' => 'Medium',
            'patterns' => ['embedly'],
            'robots_name' => 'Embedly',
            'website' => 'https://embed.ly',
            'base_score' => 30,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'iframely',
            'name' => 'Iframely',
            'category' => 'fetcher',
            'behavior' => 'link_preview',
            'organization' => 'Iframely',
            'patterns' => ['iframely'],
            'robots_name' => 'Iframely',
            'website' => 'https://iframely.com',
            'base_score' => 30,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'curl',
            'name' => 'cURL',
            'category' => 'fetcher',
            'behavior' => 'link_preview',
            'organization' => 'Open Source',
            'patterns' => ['curl/'],
            'robots_name' => '',
            'website' => 'https://curl.se',
            'base_score' => 45,
            'respects_robots' => false,
            'http_client' => true,
        ],
        [
            'id' => 'wget',
            'name' => 'Wget',
            'category' => 'fetcher',
            'behavior' => 'link_preview',
            'organization' => 'GNU',
            'patterns' => ['wget/'],
            'robots_name' => '',
            'website' => 'https://www.gnu.org/software/wget/',
            'base_score' => 45,
            'respects_robots' => false,
            'http_client' => true,
        ],
        [
            'id' => 'libwww-perl',
            'name' => 'libwww-perl',
            'category' => 'fetcher',
            'behavior' => 'link_preview',
            'organization' => 'Perl',
            'patterns' => ['libwww-perl'],
            'robots_name' => '',
            'website' => 'https://metacpan.org/pod/LWP',
            'base_score' => 50,
            'respects_robots' => false,
            'http_client' => true,
        ],
        [
            'id' => 'lwp',
            'name' => 'LWP',
            'category' => 'fetcher',
            'behavior' => 'link_preview',
            'organization' => 'Perl',
            'patterns' => ['lwp-'],
            'robots_name' => '',
            'website' => 'https://metacpan.org/pod/LWP::UserAgent',
            'base_score' => 50,
            'respects_robots' => false,
            'http_client' => true,
        ],
        [
            'id' => 'httrack',
            'name' => 'HTTrack',
            'category' => 'fetcher',
            'behavior' => 'link_preview',
            'organization' => 'Open Source',
            'patterns' => ['httrack'],
            'robots_name' => 'HTTrack',
            'website' => 'https://httrack.com',
            'base_score' => 60,
            'respects_robots' => true,
            'http_client' => true,
        ],
        [
            'id' => 'webdecoybot',
            'name' => 'WebDecoyBot',
            'category' => 'monitoring',
            'behavior' => 'monitoring',
            'organization' => 'WebDecoy',
            'patterns' => ['webdecoybot'],
            'robots_name' => 'WebDecoyBot',
            'website' => 'https://bot.webdecoy.com',
            'base_score' => 5,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'uptimerobot',
            'name' => 'UptimeRobot',
            'category' => 'monitoring',
            'behavior' => 'monitoring',
            'organization' => 'UptimeRobot',
            'patterns' => ['uptimerobot'],
            'robots_name' => 'UptimeRobot',
            'website' => 'https://uptimerobot.com',
            'base_score' => 20,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'pingdom',
            'name' => 'Pingdom',
            'category' => 'monitoring',
            'behavior' => 'monitoring',
            'organization' => 'SolarWinds',
            'patterns' => ['pingdom'],
            'robots_name' => 'Pingdom',
            'website' => 'https://pingdom.com',
            'base_score' => 20,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'statuscake',
            'name' => 'StatusCake',
            'category' => 'monitoring',
            'behavior' => 'monitoring',
            'organization' => 'StatusCake',
            'patterns' => ['statuscake'],
            'robots_name' => 'StatusCake',
            'website' => 'https://statuscake.com',
            'base_score' => 20,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'better-uptime',
            'name' => 'Better Uptime',
            'category' => 'monitoring',
            'behavior' => 'monitoring',
            'organization' => 'Better Stack',
            'patterns' => ['betteruptime'],
            'robots_name' => 'Better Uptime',
            'website' => 'https://betteruptime.com',
            'base_score' => 20,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'datadog-synthetics',
            'name' => 'Datadog Synthetics',
            'category' => 'monitoring',
            'behavior' => 'monitoring',
            'organization' => 'Datadog',
            'patterns' => ['datadog'],
            'robots_name' => 'Datadog',
            'website' => 'https://datadoghq.com',
            'base_score' => 25,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'newrelic',
            'name' => 'New Relic',
            'category' => 'monitoring',
            'behavior' => 'monitoring',
            'organization' => 'New Relic',
            'patterns' => ['newrelic'],
            'robots_name' => 'NewRelic',
            'website' => 'https://newrelic.com',
            'base_score' => 25,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'site24x7',
            'name' => 'Site24x7',
            'category' => 'monitoring',
            'behavior' => 'monitoring',
            'organization' => 'Zoho',
            'patterns' => ['site24x7'],
            'robots_name' => 'Site24x7',
            'website' => 'https://site24x7.com',
            'base_score' => 20,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'freshping',
            'name' => 'Freshping',
            'category' => 'monitoring',
            'behavior' => 'monitoring',
            'organization' => 'Freshworks',
            'patterns' => ['freshping'],
            'robots_name' => 'Freshping',
            'website' => 'https://freshping.io',
            'base_score' => 20,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'hetrixtools',
            'name' => 'HetrixTools',
            'category' => 'monitoring',
            'behavior' => 'monitoring',
            'organization' => 'HetrixTools',
            'patterns' => ['hetrixtools'],
            'robots_name' => 'HetrixTools',
            'website' => 'https://hetrixtools.com',
            'base_score' => 20,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'nodeping',
            'name' => 'NodePing',
            'category' => 'monitoring',
            'behavior' => 'monitoring',
            'organization' => 'NodePing',
            'patterns' => ['nodeping'],
            'robots_name' => 'NodePing',
            'website' => 'https://nodeping.com',
            'base_score' => 20,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'gtmetrix',
            'name' => 'GTmetrix',
            'category' => 'monitoring',
            'behavior' => 'monitoring',
            'organization' => 'GTmetrix',
            'patterns' => ['gtmetrix'],
            'robots_name' => 'GTmetrix',
            'website' => 'https://gtmetrix.com',
            'base_score' => 20,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'chrome-lighthouse',
            'name' => 'Lighthouse',
            'category' => 'monitoring',
            'behavior' => 'monitoring',
            'organization' => 'Google',
            'patterns' => ['chrome-lighthouse', 'google page speed'],
            'robots_name' => 'Chrome-Lighthouse',
            'website' => 'https://developers.google.com/speed/pagespeed/insights/',
            'base_score' => 20,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'feedly',
            'name' => 'Feedly',
            'category' => 'feed_reader',
            'behavior' => 'feeds',
            'organization' => 'Feedly',
            'patterns' => ['feedly'],
            'robots_name' => 'Feedly',
            'website' => 'https://feedly.com',
            'base_score' => 25,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'feedfetcher-google',
            'name' => 'Feedfetcher-Google',
            'category' => 'feed_reader',
            'behavior' => 'feeds',
            'organization' => 'Google',
            'patterns' => ['feedfetcher'],
            'robots_name' => 'FeedFetcher-Google',
            'website' => 'https://developers.google.com/search/docs/crawling-indexing/google-common-crawlers',
            'base_score' => 25,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'newsblur',
            'name' => 'NewsBlur',
            'category' => 'feed_reader',
            'behavior' => 'feeds',
            'organization' => 'NewsBlur',
            'patterns' => ['newsblur'],
            'robots_name' => 'NewsBlur',
            'website' => 'https://newsblur.com',
            'base_score' => 25,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'inoreader',
            'name' => 'Inoreader',
            'category' => 'feed_reader',
            'behavior' => 'feeds',
            'organization' => 'Inoreader',
            'patterns' => ['inoreader'],
            'robots_name' => 'Inoreader',
            'website' => 'https://inoreader.com',
            'base_score' => 25,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'theoldreader',
            'name' => 'The Old Reader',
            'category' => 'feed_reader',
            'behavior' => 'feeds',
            'organization' => 'The Old Reader',
            'patterns' => ['theoldreader'],
            'robots_name' => 'The Old Reader',
            'website' => 'https://theoldreader.com',
            'base_score' => 25,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'feedbin',
            'name' => 'Feedbin',
            'category' => 'feed_reader',
            'behavior' => 'feeds',
            'organization' => 'Feedbin',
            'patterns' => ['feedbin'],
            'robots_name' => 'Feedbin',
            'website' => 'https://feedbin.com',
            'base_score' => 25,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'miniflux',
            'name' => 'Miniflux',
            'category' => 'feed_reader',
            'behavior' => 'feeds',
            'organization' => 'Open Source',
            'patterns' => ['miniflux'],
            'robots_name' => 'Miniflux',
            'website' => 'https://miniflux.app',
            'base_score' => 25,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'freshrss',
            'name' => 'FreshRSS',
            'category' => 'feed_reader',
            'behavior' => 'feeds',
            'organization' => 'Open Source',
            'patterns' => ['freshrss'],
            'robots_name' => 'FreshRSS',
            'website' => 'https://freshrss.org',
            'base_score' => 25,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'commafeed',
            'name' => 'CommaFeed',
            'category' => 'feed_reader',
            'behavior' => 'feeds',
            'organization' => 'Open Source',
            'patterns' => ['commafeed'],
            'robots_name' => 'CommaFeed',
            'website' => 'https://commafeed.com',
            'base_score' => 25,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'diffbot',
            'name' => 'Diffbot',
            'category' => 'commercial_scraper',
            'behavior' => '',
            'organization' => 'Diffbot',
            'patterns' => ['diffbot'],
            'robots_name' => 'Diffbot',
            'website' => 'https://diffbot.com',
            'base_score' => 70,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'import-io',
            'name' => 'Import.io',
            'category' => 'commercial_scraper',
            'behavior' => '',
            'organization' => 'Import.io',
            'patterns' => ['import.io'],
            'robots_name' => 'Import.io',
            'website' => 'https://import.io',
            'base_score' => 65,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'bright-data',
            'name' => 'Bright Data',
            'category' => 'commercial_scraper',
            'behavior' => '',
            'organization' => 'Bright Data',
            'patterns' => ['brightdata', 'luminati'],
            'robots_name' => 'BrightData',
            'website' => 'https://brightdata.com',
            'base_score' => 70,
            'respects_robots' => false,
            'http_client' => false,
        ],
        [
            'id' => 'oxylabs',
            'name' => 'Oxylabs',
            'category' => 'commercial_scraper',
            'behavior' => '',
            'organization' => 'Oxylabs',
            'patterns' => ['oxylabs'],
            'robots_name' => 'Oxylabs',
            'website' => 'https://oxylabs.io',
            'base_score' => 70,
            'respects_robots' => false,
            'http_client' => false,
        ],
        [
            'id' => 'scrapingbee',
            'name' => 'ScrapingBee',
            'category' => 'commercial_scraper',
            'behavior' => '',
            'organization' => 'ScrapingBee',
            'patterns' => ['scrapingbee'],
            'robots_name' => 'ScrapingBee',
            'website' => 'https://scrapingbee.com',
            'base_score' => 65,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'scrapingant',
            'name' => 'ScrapingAnt',
            'category' => 'commercial_scraper',
            'behavior' => '',
            'organization' => 'ScrapingAnt',
            'patterns' => ['scrapingant'],
            'robots_name' => 'ScrapingAnt',
            'website' => 'https://scrapingant.com',
            'base_score' => 65,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'zyte',
            'name' => 'Zyte',
            'category' => 'commercial_scraper',
            'behavior' => '',
            'organization' => 'Zyte',
            'patterns' => ['zyte', 'scrapinghub'],
            'robots_name' => 'Zyte',
            'website' => 'https://zyte.com',
            'base_score' => 65,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'apify',
            'name' => 'Apify',
            'category' => 'commercial_scraper',
            'behavior' => '',
            'organization' => 'Apify',
            'patterns' => ['apify'],
            'robots_name' => 'Apify',
            'website' => 'https://apify.com',
            'base_score' => 65,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'crawlbase',
            'name' => 'Crawlbase',
            'category' => 'commercial_scraper',
            'behavior' => '',
            'organization' => 'Crawlbase',
            'patterns' => ['crawlbase'],
            'robots_name' => 'Crawlbase',
            'website' => 'https://crawlbase.com',
            'base_score' => 65,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'webscrapingapi',
            'name' => 'WebScrapingAPI',
            'category' => 'commercial_scraper',
            'behavior' => '',
            'organization' => 'WebScrapingAPI',
            'patterns' => ['webscrapingapi'],
            'robots_name' => 'WebScrapingAPI',
            'website' => 'https://webscrapingapi.com',
            'base_score' => 65,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'chatgpt-user',
            'name' => 'ChatGPT-User',
            'category' => 'ai_assistant',
            'behavior' => 'agent',
            'organization' => 'OpenAI',
            'patterns' => ['chatgpt-user'],
            'robots_name' => 'ChatGPT-User',
            'website' => 'https://openai.com',
            'base_score' => 85,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'perplexity-user',
            'name' => 'Perplexity-User',
            'category' => 'ai_assistant',
            'behavior' => 'agent',
            'organization' => 'Perplexity AI',
            'patterns' => ['perplexity-user'],
            'robots_name' => 'Perplexity-User',
            'website' => 'https://docs.perplexity.ai/guides/bots',
            'base_score' => 75,
            'respects_robots' => false,
            'http_client' => false,
        ],
        [
            'id' => 'mistralai-user',
            'name' => 'MistralAI-User',
            'category' => 'ai_assistant',
            'behavior' => 'agent',
            'organization' => 'Mistral AI',
            'patterns' => ['mistralai-user'],
            'robots_name' => 'MistralAI-User',
            'website' => 'https://docs.mistral.ai/robots',
            'base_score' => 75,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'meta-externalfetcher',
            'name' => 'Meta-ExternalFetcher',
            'category' => 'ai_assistant',
            'behavior' => 'agent',
            'organization' => 'Meta',
            'patterns' => ['meta-externalfetcher'],
            'robots_name' => 'Meta-ExternalFetcher',
            'website' => 'https://developers.facebook.com/docs/sharing/webmasters/web-crawlers',
            'base_score' => 70,
            'respects_robots' => false,
            'http_client' => false,
        ],
        [
            'id' => 'gemini-deep-research',
            'name' => 'Gemini-Deep-Research',
            'category' => 'ai_assistant',
            'behavior' => 'agent',
            'organization' => 'Google',
            'patterns' => ['gemini-deep-research'],
            'robots_name' => 'Gemini-Deep-Research',
            'website' => 'https://gemini.google.com',
            'base_score' => 65,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'copilot',
            'name' => 'Microsoft Copilot',
            'category' => 'ai_assistant',
            'behavior' => 'agent',
            'organization' => 'Microsoft',
            'patterns' => ['copilot'],
            'robots_name' => 'Copilot',
            'website' => 'https://copilot.microsoft.com',
            'base_score' => 65,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'cortana',
            'name' => 'Cortana',
            'category' => 'ai_assistant',
            'behavior' => 'agent',
            'organization' => 'Microsoft',
            'patterns' => ['cortana'],
            'robots_name' => 'Cortana',
            'website' => 'https://microsoft.com',
            'base_score' => 60,
            'respects_robots' => true,
            'http_client' => false,
        ],
        [
            'id' => 'siri',
            'name' => 'Siri',
            'category' => 'ai_assistant',
            'behavior' => 'agent',
            'organization' => 'Apple',
            'patterns' => ['siri'],
            'robots_name' => 'Siri',
            'website' => 'https://apple.com',
            'base_score' => 60,
            'respects_robots' => true,
            'http_client' => false,
        ],
    ],
];
